apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: habito-web
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/plizeth/habitoestilistes-gitops.git
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: habito-web

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      # ← Esto le dice a ArgoCD que no falle si el namespace ya existe
      - SkipDryRunOnMissingResource=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
